### ISSUE TITLE
Mangled config

### ISSUE THREAD

**Issue by michaelwisely** [redkyn/assigner#45] opened 2017-01-30 22:26 UTC
I'm not sure, but i think a Ctrl+C (sigint) caused assigner to mangle my config. It's just `{}` now.

**Comment by LinuxMercedes** [comment] 2017-01-30 22:32
Is it possible you nuked it right in the middle of `config.py` line 115? That's the only place I can see it doing something bad if killed.

I suppose we could trap SIGINT then and hold until after we finish writing.

**Comment by LinuxMercedes** [comment] 2017-08-19 18:34
I can't reproduce this and don't have enough information to determine what may have caused this behavior, so I am going to close this issue for now. If it happens again and you can provide more details on how the bug is triggered, feel free to re-open this issue!

**Closed by LinuxMercedes** 2017-08-19 18:34 UTC
